// Generated by gencpp from file machines/Conveyorstatus.msg
// DO NOT EDIT!


#ifndef MACHINES_MESSAGE_CONVEYORSTATUS_H
#define MACHINES_MESSAGE_CONVEYORSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace machines
{
template <class ContainerAllocator>
struct Conveyorstatus_
{
  typedef Conveyorstatus_<ContainerAllocator> Type;

  Conveyorstatus_()
    : header()
    , forward(0.0)
    , backward(0.0)
    , enable(0.0)
    , error()
    , ip(0.0)  {
    }
  Conveyorstatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , forward(0.0)
    , backward(0.0)
    , enable(0.0)
    , error(_alloc)
    , ip(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _forward_type;
  _forward_type forward;

   typedef double _backward_type;
  _backward_type backward;

   typedef double _enable_type;
  _enable_type enable;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_type;
  _error_type error;

   typedef double _ip_type;
  _ip_type ip;





  typedef boost::shared_ptr< ::machines::Conveyorstatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::machines::Conveyorstatus_<ContainerAllocator> const> ConstPtr;

}; // struct Conveyorstatus_

typedef ::machines::Conveyorstatus_<std::allocator<void> > Conveyorstatus;

typedef boost::shared_ptr< ::machines::Conveyorstatus > ConveyorstatusPtr;
typedef boost::shared_ptr< ::machines::Conveyorstatus const> ConveyorstatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::machines::Conveyorstatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::machines::Conveyorstatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace machines

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'machines': ['/home/dhruv/MOS_ws/src/machines/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::machines::Conveyorstatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::machines::Conveyorstatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::machines::Conveyorstatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::machines::Conveyorstatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::machines::Conveyorstatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::machines::Conveyorstatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::machines::Conveyorstatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ec79f759d0ed37cd3e5cc18185cc76f";
  }

  static const char* value(const ::machines::Conveyorstatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ec79f759d0ed37cULL;
  static const uint64_t static_value2 = 0xd3e5cc18185cc76fULL;
};

template<class ContainerAllocator>
struct DataType< ::machines::Conveyorstatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "machines/Conveyorstatus";
  }

  static const char* value(const ::machines::Conveyorstatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::machines::Conveyorstatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 forward\n"
"float64 backward\n"
"float64 enable\n"
"string error\n"
"float64 ip\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::machines::Conveyorstatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::machines::Conveyorstatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.forward);
      stream.next(m.backward);
      stream.next(m.enable);
      stream.next(m.error);
      stream.next(m.ip);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Conveyorstatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::machines::Conveyorstatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::machines::Conveyorstatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "forward: ";
    Printer<double>::stream(s, indent + "  ", v.forward);
    s << indent << "backward: ";
    Printer<double>::stream(s, indent + "  ", v.backward);
    s << indent << "enable: ";
    Printer<double>::stream(s, indent + "  ", v.enable);
    s << indent << "error: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error);
    s << indent << "ip: ";
    Printer<double>::stream(s, indent + "  ", v.ip);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MACHINES_MESSAGE_CONVEYORSTATUS_H
