// Generated by gencpp from file machines/MAMcmd.msg
// DO NOT EDIT!


#ifndef MACHINES_MESSAGE_MAMCMD_H
#define MACHINES_MESSAGE_MAMCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace machines
{
template <class ContainerAllocator>
struct MAMcmd_
{
  typedef MAMcmd_<ContainerAllocator> Type;

  MAMcmd_()
    : header()
    , moveType(0)
    , position(0.0)
    , speed(0.0)  {
    }
  MAMcmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , moveType(0)
    , position(0.0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _moveType_type;
  _moveType_type moveType;

   typedef double _position_type;
  _position_type position;

   typedef double _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::machines::MAMcmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::machines::MAMcmd_<ContainerAllocator> const> ConstPtr;

}; // struct MAMcmd_

typedef ::machines::MAMcmd_<std::allocator<void> > MAMcmd;

typedef boost::shared_ptr< ::machines::MAMcmd > MAMcmdPtr;
typedef boost::shared_ptr< ::machines::MAMcmd const> MAMcmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::machines::MAMcmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::machines::MAMcmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace machines

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'machines': ['/home/dhruv/MOS_ws/src/machines/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::machines::MAMcmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::machines::MAMcmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::machines::MAMcmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::machines::MAMcmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::machines::MAMcmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::machines::MAMcmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::machines::MAMcmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c39cd77a9e5a7c6e85eaa353b3540f2c";
  }

  static const char* value(const ::machines::MAMcmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc39cd77a9e5a7c6eULL;
  static const uint64_t static_value2 = 0x85eaa353b3540f2cULL;
};

template<class ContainerAllocator>
struct DataType< ::machines::MAMcmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "machines/MAMcmd";
  }

  static const char* value(const ::machines::MAMcmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::machines::MAMcmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"# string axis\n"
"# string tag\n"
"int8 moveType\n"
"float64 position\n"
"float64 speed\n"
"# float64 accel\n"
"# float64 decel\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::machines::MAMcmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::machines::MAMcmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.moveType);
      stream.next(m.position);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MAMcmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::machines::MAMcmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::machines::MAMcmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "moveType: ";
    Printer<int8_t>::stream(s, indent + "  ", v.moveType);
    s << indent << "position: ";
    Printer<double>::stream(s, indent + "  ", v.position);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MACHINES_MESSAGE_MAMCMD_H
